export { ActivitySection } from "./ActivitySection";
export { AwardsSection } from "./AwardsSection";
export { CertificationsSection, EducationSection } from "./BackgroundSection";
export { ContactSection } from "./ContactSection";
export { ExperienceSection } from "./ExperienceSection";
export { HeroSection } from "./HeroSection";
export { OutsideSection } from "./OutsideSection";
export { ProfileAvatar } from "./ProfileAvatar";
export { ProjectsSection } from "./ProjectsSection";
export { TechnologiesSection } from "./TechnologiesSection";
